version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID} --region ap-south-1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["46:6e:23:f0:00:75:c4:3b:11:a6:f4:46:3f:41:47:97"]  
      - run:
          name: Create Stack
          command: |
            pwd
            ls -la
            aws cloudformation deploy \
              --template-file /root/project/template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID} \
              --region ap-south-1
      #- run: return 1
      #- destroy_environment
    

workflows:
  my_workflow:
    jobs:
      - create_infrastructure

