version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID} --region=ap-south-1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy \
              --template-file https://github.com/kadhirgit/aws_infra/blob/main/.circleci/template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID} \
              --region=ap-south-1
      - run: return 1
      - destroy_environment
    

workflows:
  my_workflow:
    jobs:
      - create_infrastructure

